title = "Víctor Ávila"
baseURL = "https://avilapa.github.io/"
languageCode = "en-us"
theme = "casper"

paginate = 5
DisqusShortname = "avilapa"
Copyright = "All rights reserved - 2018"
canonifyurls = true

[[menu.main]]
identifier = "blog"
name = "Blog"
pre = "<h3>avilapa</h3>"
url = "/"
weight = 230

[[menu.main]]
identifier = "fuel-renegades"
name = "Fuel Renegades"
pre = "<h3>Projects</h3>"
url = "/fuel-renegades"
weight = 210

[[menu.main]]
identifier = "upydk"
name = "UPyDK"
url = "/upydk"
weight = 200

[params]
  description = "Videogames programming student and enthusiast"
  metadescription = ""
  cover = "images/cover-upydk.png"
  author = "Víctor Ávila Parcet"
  authorlocation = "Valencia, Spain"
  authorwebsite = "http://avilapa.github.io"
  authorbio= "Videogames programming student and enthusiast"
  logo = "images/logo-small.png"
  googleAnalyticsUserID = "UA-118883750-1"
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  # RSSLink = ""
  githubName = "avilapa"
  twitterName = "ModularSouls"
  # facebookName = ""
  # codepenName = ""
  linkedinName = "avilapa"
  # stackoverflowId = ""
  # keybaseName = ""
  # flickrName = ""
  # instagramName = ""
  # email = ""
  # pinterestName = ""
  # googlePlusName = ""

  hideHUGOSupport = true
  
  # Setting a value will load highlight.js and enable syntax highlighting using the style selected.
  # See https://github.com/isagalaev/highlight.js/tree/master/src/styles for available styles
  # A preview of above styles can be viewed at https://highlightjs.org/static/demo/
  hjsStyle = "vs"

  [params.social]
    twitter = "97torvic"