title = "Víctor Ávila"
baseURL = "https://avilapa.github.io/"
languageCode = "en-us"
theme = "casper"

paginate = 5
DisqusShortname = "avilapa-github-io"
Copyright = "All rights reserved - 2018"
canonifyurls = true

[[menu.main]]
identifier = "about"
name = "About Me"
pre = "<h3>avilapa</h3>"
url = "/about"
weight = 320

[[menu.main]]
identifier = "portfolio"
name = "Portfolio"
url = "/portfolio"
weight = 310

[[menu.main]]
identifier = "resume"
name = "Resume"
url = "/resume/resume_cv.pdf"
weight = 305

[[menu.main]]
identifier = "blog"
name = "Blog"
url = "/"
weight = 300

[[menu.main]]
pre = "<h3>Projects</h3>"
identifier = "fuel-renegades"
name = "Fuel Renegades"
url = "/fuel-renegades"
weight = 290

[[menu.main]]
identifier = "render-engine"
name = "Custom Engine"
url = "/render-engine"
weight = 280

[[menu.main]]
identifier = "vxt-raytracer"
name = "vxt Raytracer"
url = "/vxt-raytracer"
weight = 270

[[menu.main]]
identifier = "vxr-engine"
name = "vxr Engine"
url = "/vxr-engine"
weight = 260

[params]
  description = "Games programmer and computer graphics enthusiast"
  metadescription = ""
  cover = "images/cover-engine-dark.png"
  author = "Víctor Ávila Parcet"
  authorlocation = "Valencia, Spain"
  authorwebsite = "http://avilapa.github.io"
  authorbio= "Games programmer and computer graphics enthusiast"
  logo = "images/logo-large.png"
  googleAnalyticsUserID = "UA-118883750-1"
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  # RSSLink = ""
  githubName = "avilapa"
  twitterName = "97torvic"
  # facebookName = ""
  # codepenName = ""
  linkedinName = "avilapa"
  # stackoverflowId = ""
  # keybaseName = ""
  # flickrName = ""
  # instagramName = ""
  email = "victorap97@gmail.com"
  # pinterestName = ""
  # googlePlusName = ""

  hideHUGOSupport = true
  
  # Setting a value will load highlight.js and enable syntax highlighting using the style selected.
  # See https://github.com/isagalaev/highlight.js/tree/master/src/styles for available styles
  # A preview of above styles can be viewed at https://highlightjs.org/static/demo/
  hjsStyle = "vs"

  [params.social]
    twitter = "97torvic"